const SYSTEM_PROMPT = `You are the ZYNNOX Website Builder Agent.
Generate production-ready React/Tailwind-friendly website files.
Return JSON with projectStructure, files [{path, language, content}], instructions, previewNotes.`;

function fallbackWebsite({ prompt, type, style }) {
  const title = prompt.split(" ").slice(0, 8).join(" ") || "ZYNNOX Website";
  return {
    projectStructure: {
      "src/pages": ["GeneratedHome.jsx"],
      "src/components": ["GeneratedShell.jsx"],
      "src/styles": ["generated.css"]
    },
    files: [
      {
        path: "src/pages/GeneratedHome.jsx",
        language: "jsx",
        content: `export default function GeneratedHome() {
  return (
    <main className="generated-site ${style}">
      <section className="hero">
        <p className="eyebrow">${type} website</p>
        <h1>${title}</h1>
        <p>Generated by ZYNNOX Website Builder. Replace this copy with production content and connect real data sources as needed.</p>
        <button>Launch preview</button>
      </section>
    </main>
  );
}
`
      },
      {
        path: "src/styles/generated.css",
        language: "css",
        content: `.generated-site { min-height: 100vh; background: #06111f; color: #f8fafc; font-family: Inter, system-ui, sans-serif; }
.hero { max-width: 1120px; margin: 0 auto; padding: 96px 24px; }
.eyebrow { color: #22d3ee; text-transform: uppercase; letter-spacing: .12em; font-size: 12px; }
h1 { font-size: clamp(40px, 8vw, 88px); line-height: 1; margin: 12px 0; }
p { max-width: 680px; color: #cbd5e1; }
button { margin-top: 24px; border: 0; border-radius: 8px; background: #22d3ee; color: #06111f; padding: 12px 18px; font-weight: 700; }`
      }
    ],
    instructions: "Place files in a React/Vite project. Tailwind classes can be substituted if Tailwind is configured.",
    previewNotes: "Fallback generation is active. Configure AI_MODE=production for richer multi-page output."
  };
}

export const websiteBuilderAgent = {
  id: "website-builder",
  name: "Website Builder Agent",
  systemPrompt: SYSTEM_PROMPT,
  async run({ prompt, type, style, pages, ai }) {
    try {
      const result = await ai.json(
        [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: JSON.stringify({ prompt, type, style, pages }) }
        ],
        { maxTokens: 2500 }
      );
      return {
        projectStructure: result.projectStructure || fallbackWebsite({ prompt, type, style }).projectStructure,
        files: Array.isArray(result.files) && result.files.length ? result.files : fallbackWebsite({ prompt, type, style }).files,
        instructions: result.instructions || "Review generated files before shipping.",
        previewNotes: result.previewNotes || "Generated website output is ready for implementation."
      };
    } catch {
      return fallbackWebsite({ prompt, type, style });
    }
  }
};
